AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Laravel Serverless Application'

Resources:
  MyLaravelFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'public/index.php'
      Runtime: 'provided.al2'
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
